name: PR Check (GitFlow)

on:
    pull_request:
        branches: [develop]

jobs:
    pr-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build --if-present

            - name: Test
              run: npm test

            # - name: Check code coverage
            #   run: |
            #       npm run test:coverage
            #       COVERAGE=$(cat coverage/lcov.info | grep -A 1 "Total" | tail -n 1 | awk '{print $2}' | cut -d'%' -f1)
            #       if (( $(echo "$COVERAGE < 80" | bc) )); then
            #           echo "Code coverage ($COVERAGE%) is below minimum threshold (80%)"
            #           exit 1
            #       fi

    automerge:
        needs: pr-check
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login != 'github-actions[bot]'

        steps:
            - name: Enable auto-merge
              uses: peter-evans/enable-pull-request-automerge@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  pull-request-number: ${{ github.event.pull_request.number }}
                  merge_method: squash
