name: DEVELOP

on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest

        name: Build and test

        steps:
            - name: Show pre-installed Node.js version
              run: node --version

            - uses: actions/checkout@v4

            - name: Install Node.js via nvm using .nvmrc
              shell: bash --login {0}
              run: |
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install --latest-npm --no-progress
                  echo "$(dirname $(nvm which node))" >> $GITHUB_PATH

            - name: Show newly installed Node.js version
              run: node --version

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build --if-present

            - name: Run tests
              run: npm test

    increment-version:
        runs-on: ubuntu-latest

        needs: build

        name: Increment version and push changes

        steps:
            - uses: actions/checkout@v4

            - name: Install Node.js via nvm using .nvmrc
              shell: bash --login {0}
              run: |
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install --latest-npm --no-progress
                  echo "$(dirname $(nvm which node))" >> $GITHUB_PATH

            - name: Show newly installed Node.js version
              run: node --version

            - name: Increment version
              run: npm version --no-git-tag-version prerelease --preid beta

            - name: Config GIT user
              run: |
                  git config --local user.name 'an employee of the 7G sector'
                  git config --local user.email ''

            - name: Commit and push new version
              run: |
                  git add package.json
                  git commit -m "New version"
                  git push

    publish:
        runs-on: ubuntu-latest

        needs: [build, increment-version]

        name: Publish package

        steps:
            - uses: actions/checkout@v4

            - name: Install Node.js via nvm using .nvmrc
              shell: bash --login {0}
              run: |
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install --latest-npm --no-progress
                  echo "$(dirname $(nvm which node))" >> $GITHUB_PATH

            - name: Pull last changes
              run: |
                  git fetch origin develop --unshallow || true
                  git pull origin develop

            - name: Install dependencies
              run: npm ci

            - name: Create pack
              run: npm pack

            - name: Publish package
              run: npm publish --scope daaxar --tag beta
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
