name: PULL REQUEST

on:
    pull_request:
        branches: [develop, main]

jobs:
    build:
        runs-on: ubuntu-latest

        name: Build and test

        steps:
            - name: Show pre-installed Node.js version
              run: node --version

            - uses: actions/checkout@v4

            - name: Install Node.js via nvm using .nvmrc
              shell: bash --login {0}
              run: |
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install --latest-npm --no-progress
                  echo "$(dirname $(nvm which node))" >> $GITHUB_PATH

            - name: Show newly installed Node.js version
              run: node --version

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build --if-present

            - name: Run tests
              run: npm test
