name: PULL REQUEST

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Upgrade to npm@8
      run: npm install -g npm@8

    - name: Install dependencies 
      run: npm ci
          
    - name: Build project
      run: npm run build --if-present
          
    - name: Run tests
      run: npm test
