name: TAG RELEASE

on:
    push:
        tags:
            - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
    validate-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Validate SemVer Tag
              run: |
                  if [[ ! "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                      echo "Error: Tag must follow SemVer format (e.g., v1.0.0)"
                      exit 1
                  fi

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  registry-url: 'https://npm.pkg.github.com/'

            - name: Auth to GitHub Packages
              run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build --if-present

            - name: Publish with specific tag
              run: npm publish --tag ${GITHUB_REF#refs/tags/v}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
